app/models.py
from datetime import datetime
import hashlib
from werkzeug.security import  generate_password_hash,check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app,request
from flask_login import UserMixin,AnonymousUserMixin
from . import db,login_manager

class Permission:
    OPERATE = 0x01
    APPROVE = 0x02
    ADMINISTOR=0x80

class Role(db.Model):
    __tablename__ = 'roles'
    id=db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(64),unique=True)
    default = db.Column(db.Boolean,default=False,index=True)
    permissions = db.Column(db.Integer)
    users =db.relationship('User',backref='role',lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles={
            'Operator':(Permission.OPERATE,True),
            'Manager':(Permission.APPROVE,False),
            'Administrator':(0xff,False)
        }
        for r in roles:
            role=Role.query.filter_by(name=r).first()
            if role is None:
                role=Role(name=r)
            role.permissions=roles[r][0]
            role.default=roles[r][1]
            db.session.add(role)

        db.session.commit()

    def __repr__(self):
        return '<Role %r>' % self.name

class User(UserMixin,db.Model):
    __tablename__= 'users'
    id = db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(64))
    user_id= db.Column(db.String(10),unique=True,index=True)
    status=db.Column(db.Boolean,default=True)
    role_id=db.Column(db.Integer,db.ForeignKey('roles.id'))
    password_hash=db.Column(db.String(128))

    @staticmethod
    def init_users():
        userlist={
            '001':('o001','001','Operator'),
            '002':('m002','002','Manager'),
            '003':('a003','003','ADMINISTOR')
        }
        for u in userlist:
            role =Role.query.filter_by(name=userlist[u][2]).first()
            if role is None:
                role=Role.query.filter_by(default=True).first()
            u=User(user_id=userlist[u][1],username=userlist[u][0],role=role,password=userlist[u][1])

            db.session.add(u)

        db.session.commit()

    def __init__(self,**kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            self.role=Role.query.filter_by(default=True).first()


    @property
    def password(self):
        raise AttributeError("password is not a readable attribute")

    @password.setter
    def password(self,password):
        self.password_hash=generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)

    def can(self,permissions):
        return self.role is not None and \
               (self.role.permissions & permissions) == permissions

    def is_administrator(self):
        return self.can(Permission.OPERATE)

    def get_user_by_id(user_id):
        return User.query.filter_by(user_id=user_id).first()



    def __repr__(self):
        return '<User %r>' % self.username

class AnonymousUser(AnonymousUserMixin):
    def can(selfself,permissions):
        return False
    def is_adminsitrator(self):
        return False

login_manager.anonymous_user = AnonymousUser

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class LG(db.Model):
    __tablename__ = 'lg_gts'
    id = db.Column(db.Integer,primary_key=True)
    type = db.Column(db.String(5), index=True)
    no= db.Column(db.String(20),unique=True,index=True)
    companyname = db.Column(db.String(64))
    amt = db.Column(db.String(64))

    custom_no=db.Column(db.String(10))

    createdate = db.Column(db.String(8),index=True)
    updatedate = db.Column(db.String(8))
    status = db.Column(db.Integer)
    def __init__(self,**kwargs):
        super(LG,self).__init__(**kwargs)
    def get_by_no(no):
        return LG.query.filter_by(no=no).first()

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,BooleanField,SelectField,SubmitField,FieldList,HiddenField
from wtforms.validators import Required,Length,Regexp
from ..models import Role,User,LG

class LGDetailForm(FlaskForm):
    #how to put a hidden fi


    lg_no = StringField('保函编号', label='保函编号')

    lg_companyname=StringField('公司名称')
    lg_custom_no=StringField('海关编号')
    submit = SubmitField('提交')

    def __init__(self,lg,*args,**kwargs):
        super(LGDetailForm,self).__init__(*args,**kwargs)
        self.lg=lg

class LGEqueryForm(FlaskForm):
    #how to put a hidden fi

    lg_no = StringField('保函编号')



    submit = SubmitField('提交')

    def __init__(self,*args,**kwargs):
        super(LGEqueryForm,self).__init__(*args,**kwargs)

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from flask_moment import Moment
from flask_login import LoginManager
from config import config

bootstrap = Bootstrap()
mail=Mail()
moment=Moment()
db=SQLAlchemy()

login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'

def create_app(config_name):
    app=Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    moment.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)

from . import views,errors
from ..models import Permission

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

app/main/views.py
from flask import render_template,redirect,url_for,abort,flash
from flask_login import login_required,current_user
from . import main
from .forms import LGDetailForm,LGEqueryForm
from .. import db
from ..models import Role,User,LG


@main.route('/index')
def index():
    return render_template('index.html')




@main.route('/enquery', methods=['GET', 'POST'])
@login_required
def enquery():

    form = LGEqueryForm()
    if form.validate_on_submit():
        lg = LG.query.filter_by(id=form.lg_no).first()
        if lg is not None:
            form1=LGDetailForm()
            return render_template('main/detail_lg',form=form1)
        flash('lg_no not found.')
    return render_template('main/enquery_lg.html',form=form)


@main.route('/update_lg/<lg_no>')
@login_required
def update_lg(lg_no):
    lg=LG.query.filter_by(no=lg_no).first
    if lg is None:
        flash('the lg not existed')
        return redirect(url_for('.index'))
    form = LGDetailForm(lg=lg)
    if form.validate_on_submit():
        lg.lg_custom_no=form.lg_custom_no.data
        lg.lg_status = 1
        db.session.add(lg)
        flash('lg updated')
        return redirect(url_for('.approve_lg',lg_no=lg.no))
    form.lg_no.data=lg.lg_no
    form.lg_companyname=lg.lg_companyname
    form.lg_custom_no=lg.lg_custom_no
    form.lg_amt = lg.lg_amt
    return render_template('main/update_lg.html',form=form,lg=lg)

@main.route('/detail_lg/<lg_no>')
@login_required
def approve_lg(lg_no):
    lg = LG.query.filter_by(no=lg_no).first
    if lg is None:
        flash('the lg not existed')
        return redirect(url_for('.index'))
    form = LGDetailForm(lg=lg)
    if form.validate_on_submit():
        if lg.lg_status==1:
            lg.lg_status=2
        else:
            lg.lg_status=1

        db.session.add(lg)
        if lg.lg_status==1:
            flash('lg custom_no updated')
        else:
            flash('lg custom_no approved')
        return redirect(url_for('main/enquery_lg'))
    form.lg_no.data=lg.lg_no
    form.lg_companyname=lg.lg_companyname
    form.lg_custom_no=lg.lg_custom_no
    form.lg_amt = lg.lg_amt
    form.lg_status = lg.lg_status
    if lg.lg_status==0:
        form.submit.data='update'
    else:
        form.submit.data='approve'
    return render_template('main/update_lg.html',form=form,lg=lg)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}BOCLN{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">LG_Gateway</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}


                <li><a href="{{ url_for('main.enquery')}}">lg_details</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">

                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
{% endblock %}

app/templates/main/detail_lg.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Login{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Login</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}

</div>
{% endblock %}

app/templates/main/enquery_lg.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Enquery{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Enquery here you are</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}

</div>
{% endblock %}

app/templates/main/update_lg.html
{% extends "base.html" %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h1>
</div>
{% endblock %}